-- AfricanArtistShop production schema for Supabase PostgreSQL
-- Run this in Supabase SQL Editor before switching the application runtime.

create table if not exists users (
  id bigint generated by default as identity primary key,
  name text not null,
  email text unique not null,
  password_hash text not null,
  role text not null default 'customer',
  created_at timestamptz default now()
);

create table if not exists login_tokens (
  token_hash text primary key,
  user_id bigint not null references users(id),
  expires_at bigint not null,
  created_at timestamptz default now()
);

create table if not exists artists (
  id bigint generated by default as identity primary key,
  user_id bigint unique references users(id),
  name text not null,
  specialty text,
  bio text,
  image_url text,
  artist_type text default 'professional',
  age_group text default 'adult',
  guardian_name text,
  guardian_phone text,
  status text not null default 'pending',
  registration_paid integer default 0,
  payment_reference text,
  registration_currency text,
  registration_amount numeric default 0,
  created_at timestamptz default now()
);

create table if not exists artworks (
  id bigint generated by default as identity primary key,
  artist_id bigint not null references artists(id),
  title text not null,
  medium text not null,
  size text,
  price numeric not null,
  description text,
  image_url text not null,
  availability text default 'Available',
  age_group text default 'adult',
  status text not null default 'pending',
  created_at timestamptz default now()
);

create table if not exists supplies (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  description text,
  image_url text not null,
  price numeric not null,
  stock integer default 0,
  unit text default 'piece',
  active integer default 1,
  created_at timestamptz default now()
);

create table if not exists orders (
  id bigint generated by default as identity primary key,
  user_id bigint references users(id),
  customer_name text,
  customer_email text,
  whatsapp text,
  address text,
  total numeric not null,
  listing_fees numeric default 0,
  commission numeric default 0,
  status text default 'pending',
  created_at timestamptz default now()
);

create table if not exists order_items (
  id bigint generated by default as identity primary key,
  order_id bigint references orders(id),
  item_type text not null,
  item_id bigint,
  title text,
  price numeric,
  quantity integer,
  artist_id bigint
);

create table if not exists transactions (
  id bigint generated by default as identity primary key,
  order_id bigint,
  user_id bigint,
  provider text,
  reference text unique,
  status text,
  amount numeric,
  currency text,
  purpose text,
  artist_type text,
  metadata text,
  created_at timestamptz default now()
);

create table if not exists training_requests (
  id bigint generated by default as identity primary key,
  user_id bigint,
  child_name text not null,
  child_age integer not null,
  guardian_name text not null,
  guardian_phone text not null,
  email text,
  location text,
  training_type text,
  notes text,
  status text default 'pending',
  created_at timestamptz default now()
);

create table if not exists artist_daily_stats (
  id bigint generated by default as identity primary key,
  artist_id bigint not null references artists(id),
  day text not null,
  views integer default 0,
  sales integer default 0,
  unique(artist_id, day)
);

create table if not exists settings (
  key text primary key,
  value text
);

create table if not exists user_sessions (
  sid text primary key,
  sess jsonb not null,
  expire timestamptz not null
);

-- Private artwork storage bucket. The application should use the Supabase
-- Storage API with the server-side service-role key for uploads.
insert into storage.buckets (id, name, public)
values ('artworks', 'artworks', true)
on conflict (id) do update set public = true;

create index if not exists idx_artworks_artist on artworks(artist_id);
create index if not exists idx_artworks_status on artworks(status);
create index if not exists idx_artists_status on artists(status);
create index if not exists idx_orders_user on orders(user_id);
create index if not exists idx_order_items_order on order_items(order_id);
create index if not exists idx_transactions_reference on transactions(reference);
