require('dotenv').config();
const path=require('path'); const fs=require('fs'); const crypto=require('crypto');
const express=require('express'); const session=require('express-session');
const bcrypt=require('bcryptjs'); const multer=require('multer'); const Database=require('better-sqlite3');
const app=express(); const PORT=process.env.PORT||3000;
app.set('trust proxy',1);
const DB_PATH=process.env.DB_PATH||path.join(__dirname,'africanartistshop.db');
const uploadDir=path.join(__dirname,'public','uploads'); fs.mkdirSync(uploadDir,{recursive:true});
const db=new Database(DB_PATH); db.pragma('journal_mode=WAL');
app.use(express.json({verify:(req,res,buf)=>{req.rawBody=buf}})); app.use(express.urlencoded({extended:true,limit:'1mb'}));
app.use((req,res,next)=>{res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('X-Frame-Options','SAMEORIGIN');res.setHeader('Referrer-Policy','strict-origin-when-cross-origin');res.setHeader('Permissions-Policy','camera=(),microphone=(),geolocation=()');next()});
const OWNER_EMAIL=process.env.OWNER_EMAIL||'mojibolapeace@gmail.com';
const EMAIL_FROM=process.env.EMAIL_FROM||'onboarding@resend.dev';
async function sendEmail({to,subject,html}){if(!process.env.RESEND_API_KEY)return false;try{const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:'Bearer '+process.env.RESEND_API_KEY,'Content-Type':'application/json'},body:JSON.stringify({from:EMAIL_FROM,to:Array.isArray(to)?to:[to],subject,html})});if(!r.ok){console.error('Email send failed',await r.text());return false}return true}catch(e){console.error('Email error',e.message);return false}}
const rateBuckets=new Map();
function escHtml(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]) )}
function rateLimit(max=30,windowMs=60000){return (req,res,next)=>{const key=req.ip+':'+req.path;const now=Date.now();let b=rateBuckets.get(key);if(!b||now-b.start>windowMs)b={start:now,count:0};b.count++;rateBuckets.set(key,b);if(b.count>max)return res.status(429).json({error:'Too many requests. Please try again shortly.'});next()}};

app.use(session({secret:process.env.SESSION_SECRET||'change-me',resave:false,saveUninitialized:false,cookie:{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',maxAge:1000*60*60*24*30}}));
const storage=multer.diskStorage({destination:uploadDir,filename:(req,file,cb)=>cb(null,Date.now()+'-'+file.originalname.replace(/[^a-zA-Z0-9._-]/g,'_'))});
const upload=multer({storage,limits:{fileSize:8*1024*1024},fileFilter:(req,file,cb)=>{const allowed=['image/jpeg','image/png','image/webp','image/gif'];if(!allowed.includes(file.mimetype))return cb(new Error('Only JPG, PNG, WEBP or GIF images are allowed'));cb(null,true)}});
function init(){
db.exec(`
CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,email TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'customer',created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS login_tokens(token_hash TEXT PRIMARY KEY,user_id INTEGER NOT NULL,expires_at INTEGER NOT NULL,created_at TEXT DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(id));
CREATE TABLE IF NOT EXISTS artists(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER UNIQUE,name TEXT NOT NULL,specialty TEXT,bio TEXT,image_url TEXT,artist_type TEXT DEFAULT 'professional',age_group TEXT DEFAULT 'adult',guardian_name TEXT,guardian_phone TEXT,status TEXT NOT NULL DEFAULT 'pending',created_at TEXT DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(id));
CREATE TABLE IF NOT EXISTS artworks(id INTEGER PRIMARY KEY AUTOINCREMENT,artist_id INTEGER NOT NULL,title TEXT NOT NULL,medium TEXT NOT NULL,size TEXT,price REAL NOT NULL,description TEXT,image_url TEXT NOT NULL,availability TEXT DEFAULT 'Available',age_group TEXT DEFAULT 'adult',status TEXT NOT NULL DEFAULT 'pending',created_at TEXT DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(artist_id) REFERENCES artists(id));
CREATE TABLE IF NOT EXISTS supplies(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,category TEXT NOT NULL,description TEXT,image_url TEXT NOT NULL,price REAL NOT NULL,stock INTEGER DEFAULT 0,unit TEXT DEFAULT 'piece',active INTEGER DEFAULT 1,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS orders(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER,customer_name TEXT,customer_email TEXT,whatsapp TEXT,address TEXT,total REAL NOT NULL,listing_fees REAL DEFAULT 0,commission REAL DEFAULT 0,status TEXT DEFAULT 'pending',created_at TEXT DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(id));
CREATE TABLE IF NOT EXISTS order_items(id INTEGER PRIMARY KEY AUTOINCREMENT,order_id INTEGER,item_type TEXT NOT NULL,item_id INTEGER,title TEXT,price REAL,quantity INTEGER,artist_id INTEGER,FOREIGN KEY(order_id) REFERENCES orders(id));
CREATE TABLE IF NOT EXISTS transactions(id INTEGER PRIMARY KEY AUTOINCREMENT,order_id INTEGER,user_id INTEGER,provider TEXT,reference TEXT,status TEXT,amount REAL,currency TEXT,purpose TEXT,artist_type TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS training_requests(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER,child_name TEXT NOT NULL,child_age INTEGER NOT NULL,guardian_name TEXT NOT NULL,guardian_phone TEXT NOT NULL,email TEXT,location TEXT,training_type TEXT,notes TEXT,status TEXT DEFAULT 'pending',created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS artist_daily_stats(id INTEGER PRIMARY KEY AUTOINCREMENT,artist_id INTEGER NOT NULL,day TEXT NOT NULL,views INTEGER DEFAULT 0,sales INTEGER DEFAULT 0,UNIQUE(artist_id,day));
CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY,value TEXT);
`);
const set=(k,v)=>db.prepare('INSERT OR IGNORE INTO settings(key,value) VALUES(?,?)').run(k,String(v));
const addColumn=(table,column,definition)=>{try{db.exec(`ALTER TABLE ${table} ADD COLUMN ${column} ${definition}`)}catch(e){}};
addColumn('artists','registration_paid',"INTEGER DEFAULT 0");
addColumn('artists','payment_reference',"TEXT");
addColumn('artists','registration_currency',"TEXT");
addColumn('artists','registration_amount',"REAL DEFAULT 0");
addColumn('transactions','user_id',"INTEGER");
addColumn('transactions','currency',"TEXT");
addColumn('transactions','purpose',"TEXT");
addColumn('transactions','artist_type',"TEXT");
addColumn('transactions','metadata',"TEXT");
const TIER_RULES={kid:{label:'Young / Kid Artist',min:3,max:5,fee:{NGN:4000,USD:3},age:'4-18'},professional:{label:'Professional Artist',min:5,max:7,fee:{NGN:13000,USD:10}},signature:{label:'Signature Artist',min:8,max:10,fee:{NGN:0,USD:0}}};
function tierRule(type){return TIER_RULES[type]||TIER_RULES.professional}
function today(){return new Date().toISOString().slice(0,10)}
function recordArtistStat(artistId,field,amount=1){const d=today();db.prepare('INSERT INTO artist_daily_stats(artist_id,day,views,sales) VALUES(?,?,0,0) ON CONFLICT(artist_id,day) DO NOTHING').run(artistId,d);db.prepare(`UPDATE artist_daily_stats SET ${field}=${field}+? WHERE artist_id=? AND day=?`).run(amount,artistId,d)}
async function paystack(pathname,options={}){if(!process.env.PAYSTACK_SECRET_KEY)throw new Error('Paystack is not configured. Add PAYSTACK_SECRET_KEY in Render environment variables.');const r=await fetch('https://api.paystack.co'+pathname,{...options,headers:{Authorization:'Bearer '+process.env.PAYSTACK_SECRET_KEY,'Content-Type':'application/json',...(options.headers||{})}});const data=await r.json();if(!r.ok||!data.status)throw new Error(data.message||'Paystack request failed');return data}
set('artist_listing_fee','5000'); set('sales_commission_percent','10');
const admin=db.prepare('SELECT id FROM users WHERE email=?').get('admin@africanartistshop.com');
if(!admin) db.prepare('INSERT INTO users(name,email,password_hash,role) VALUES(?,?,?,?)').run('AfricanArtistShop Admin','admin@africanartistshop.com',bcrypt.hashSync('demo1234',10),'admin');
let a=db.prepare('SELECT id FROM users WHERE email=?').get('peace@example.com');
if(!a){const info=db.prepare('INSERT INTO users(name,email,password_hash,role) VALUES(?,?,?,?)').run('Peace Ayodeji','peace@example.com',bcrypt.hashSync('demo1234',10),'artist');const ar=db.prepare('INSERT INTO artists(user_id,name,specialty,bio,image_url,artist_type,age_group,registration_paid,status) VALUES(?,?,?,?,?,?,?,?,?)').run(info.lastInsertRowid,'Peace Ayodeji','Painting','African artist and creator. Featured collection: Face of Time.','/uploads/peace-ayodeji-profile.jpg','professional','adult',1,'approved');db.prepare('INSERT INTO artworks(artist_id,title,medium,size,price,description,image_url,availability,age_group,status) VALUES(?,?,?,?,?,?,?,?,?,?)').run(ar.lastInsertRowid,'Face of Time','Painting','24 x 36 in',85000,'Face of Time is an imaginative portrait exploring time, identity and expression.','/uploads/face-of-time.jpg','Available','adult','approved');}else{db.prepare("UPDATE users SET name='Peace Ayodeji' WHERE id=?").run(a.id);db.prepare("UPDATE artists SET name='Peace Ayodeji',specialty='Painting',bio='African artist and creator. Featured collection: Face of Time.',image_url='/uploads/peace-ayodeji-profile.jpg',artist_type='professional',age_group='adult',registration_paid=1,status='approved' WHERE user_id=?").run(a.id);const ar=db.prepare('SELECT id FROM artists WHERE user_id=?').get(a.id);if(ar){const w=db.prepare('SELECT id FROM artworks WHERE artist_id=? AND title=?').get(ar.id,'Face of Time');if(w)db.prepare("UPDATE artworks SET medium='Painting',size='24 x 36 in',description='Face of Time is an imaginative portrait exploring time, identity and expression.',image_url='/uploads/face-of-time.jpg',availability='Available',age_group='adult',status='approved' WHERE id=?").run(w.id);else db.prepare('INSERT INTO artworks(artist_id,title,medium,size,price,description,image_url,availability,age_group,status) VALUES(?,?,?,?,?,?,?,?,?,?)').run(ar.id,'Face of Time','Painting','24 x 36 in',85000,'Face of Time is an imaginative portrait exploring time, identity and expression.','/uploads/face-of-time.jpg','Available','adult','approved')}}
if(db.prepare('SELECT COUNT(*) c FROM supplies').get().c===0){
const ins=db.prepare('INSERT INTO supplies(name,category,description,image_url,price,stock,unit) VALUES(?,?,?,?,?,?,?)');
[
['Acrylic Paint Set','Paints','Rich starter acrylic set for canvas and mixed-media work.','https://www.mgstationeryonline.com.my/images/com_hikashop/upload/mg_apln6594__96-acrylic_paint_set_12__36_colors-06_1547355164.jpg',18500,20,'set'],
['Artist Brush Collection','Brushes','Assorted round, flat and detail brushes for artists.','https://i5.walmartimages.com/seo/25pcs-Paint-Brush-Set-Acrylic-Paint-Brushes-Professional-Artist-Series-Wide-Flat-Filbert-Fan-Dagger-Cat-Tongue-Round-Angle-Rigger-Oil-Acrylic-Canvas_15d9974f-50ac-4633-83e1-13cd5db579b9.ec32c8898a62ca2709a48ac2588591c2.jpeg',9500,30,'pack'],
['Cotton Canvas 24 × 36 in','Canvas','Primed cotton canvas ready for painting.','https://i5.walmartimages.com/asr/242f0fc4-cdba-4087-9288-bd083bbde5d1.cab6bbb8c418e65a030ccd72b54578e2.jpeg',12000,25,'piece'],
['Wooden Tabletop Easel','Easels','Compact wooden easel for studio or tabletop painting.','https://www.arthurdaleys.com.au/content/product/full/MONT_MARTE___SIGNATURE___TRADITIONAL_TABLETOP_EASEL___MEDIUM-2739-1063.jpg',22000,12,'piece'],
['Watercolour Paper Pad','Paper','Acid-free paper for watercolour and ink studies.','https://www.pictorshop.ro/21604-large_default/bloc-hartie-pictura-acuarela-winsor-newton.jpg',7500,35,'pad'],
['Palette Knife Set','Tools','Metal palette knives for texture and impasto techniques.','https://cottonwoodinthepark.com/cdn/shop/files/5367c5609408468a6dcef2d93286601e0125f03f1880684131c53f846ec00d09.jpg?v=1721698795&width=1445',6500,18,'set']
].forEach(x=>ins.run(...x));
}}
/* Keep the catalogue images matched to the actual products even when the database was seeded on an older deployment. */
function refreshSupplyImages(){
  const imgs={
    'Acrylic Paint Set':'https://www.mgstationeryonline.com.my/images/com_hikashop/upload/mg_apln6594__96-acrylic_paint_set_12__36_colors-06_1547355164.jpg',
    'Artist Brush Collection':'https://i5.walmartimages.com/seo/25pcs-Paint-Brush-Set-Acrylic-Paint-Brushes-Professional-Artist-Series-Wide-Flat-Filbert-Fan-Dagger-Cat-Tongue-Round-Angle-Rigger-Oil-Acrylic-Canvas_15d9974f-50ac-4633-83e1-13cd5db579b9.ec32c8898a62ca2709a48ac2588591c2.jpeg',
    'Cotton Canvas 24 × 36 in':'https://i5.walmartimages.com/asr/242f0fc4-cdba-4087-9288-bd083bbde5d1.cab6bbb8c418e65a030ccd72b54578e2.jpeg',
    'Wooden Tabletop Easel':'https://www.arthurdaleys.com.au/content/product/full/MONT_MARTE___SIGNATURE___TRADITIONAL_TABLETOP_EASEL___MEDIUM-2739-1063.jpg',
    'Watercolour Paper Pad':'https://www.pictorshop.ro/21604-large_default/bloc-hartie-pictura-acuarela-winsor-newton.jpg',
    'Palette Knife Set':'https://cottonwoodinthepark.com/cdn/shop/files/5367c5609408468a6dcef2d93286601e0125f03f1880684131c53f846ec00d09.jpg?v=1721698795&width=1445'
  };
  const q=db.prepare('UPDATE supplies SET image_url=? WHERE name=?');
  Object.entries(imgs).forEach(([name,url])=>q.run(url,name));
}
refreshSupplyImages();
init();
function cookieValue(req,name){const raw=req.headers.cookie||'';const part=raw.split(';').map(x=>x.trim()).find(x=>x.startsWith(name+'='));return part?decodeURIComponent(part.slice(name.length+1)):''}
function issueRememberToken(res,userId){const raw=crypto.randomBytes(32).toString('hex');const hash=crypto.createHash('sha256').update(raw).digest('hex');const expires=Date.now()+1000*60*60*24*30;db.prepare('INSERT INTO login_tokens(token_hash,user_id,expires_at) VALUES(?,?,?)').run(hash,userId,expires);res.setHeader('Set-Cookie',`aas_remember=${encodeURIComponent(raw)}; Max-Age=${60*60*24*30}; Path=/; HttpOnly; SameSite=Lax${process.env.NODE_ENV==='production'?'; Secure':''}`);return raw}
function forgetRememberToken(req,res){const raw=cookieValue(req,'aas_remember');if(raw){const hash=crypto.createHash('sha256').update(raw).digest('hex');db.prepare('DELETE FROM login_tokens WHERE token_hash=?').run(hash)}res.clearCookie('aas_remember',{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',path:'/'})}
app.use((req,res,next)=>{if(req.session.user)return next();const raw=cookieValue(req,'aas_remember');if(!raw)return next();try{const hash=crypto.createHash('sha256').update(raw).digest('hex');const row=db.prepare('SELECT lt.user_id,u.id,u.name,u.email,u.role FROM login_tokens lt JOIN users u ON u.id=lt.user_id WHERE lt.token_hash=? AND lt.expires_at>?').get(hash,Date.now());if(row){req.session.user={id:row.id,name:row.name,email:row.email,role:row.role};req.session.save(()=>next());return}db.prepare('DELETE FROM login_tokens WHERE token_hash=?').run(hash)}catch(e){}next()}
function auth(req,res,next){if(!req.session.user)return res.status(401).json({error:'Authentication required'});next()}
function role(r){return (req,res,next)=>{if(!req.session.user||req.session.user.role!==r)return res.status(403).json({error:'Forbidden'});next()}}
function setting(k){return Number(db.prepare('SELECT value FROM settings WHERE key=?').get(k)?.value||0)}
app.get('/api/health',(req,res)=>res.json({ok:true}));
app.get('/api/me',(req,res)=>res.json({user:req.session.user||null}));
app.post('/api/register',rateLimit(8,60000),(req,res)=>{try{const {name,email,password}=req.body;if(!name||!email||!password)return res.status(400).json({error:'Name, email and password are required'});const exists=db.prepare('SELECT id FROM users WHERE email=?').get(email.toLowerCase());if(exists)return res.status(409).json({error:'Email already registered'});const info=db.prepare('INSERT INTO users(name,email,password_hash,role) VALUES(?,?,?,?)').run(name,email.toLowerCase(),bcrypt.hashSync(password,10),'customer');const user={id:info.lastInsertRowid,name,email:email.toLowerCase(),role:'customer'};req.session.user=user;issueRememberToken(res,user.id);res.json(user)}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/login',rateLimit(12,60000),(req,res)=>{const {email,password}=req.body;const u=db.prepare('SELECT * FROM users WHERE email=?').get((email||'').toLowerCase());if(!u||!bcrypt.compareSync(password||'',u.password_hash))return res.status(401).json({error:'Invalid email or password'});const user={id:u.id,name:u.name,email:u.email,role:u.role};req.session.user=user;issueRememberToken(res,user.id);res.json(user)});
app.post('/api/logout',(req,res)=>{forgetRememberToken(req,res);req.session.destroy(()=>res.json({ok:true}))});
app.get('/api/artworks',(req,res)=>{const q='%'+(req.query.q||'')+'%';const m=req.query.medium||'';let sql=`SELECT a.*,ar.name artist_name FROM artworks a JOIN artists ar ON ar.id=a.artist_id WHERE a.status='approved' AND ar.status='approved' AND (a.title LIKE ? OR a.medium LIKE ? OR ar.name LIKE ?)`;let params=[q,q,q];if(m){sql+=' AND a.medium=?';params.push(m)}if(req.query.age){sql+=' AND a.age_group=?';params.push(req.query.age)}sql+=' ORDER BY a.created_at DESC';res.json(db.prepare(sql).all(...params))});
app.get('/api/artworks/:id',(req,res)=>{const x=db.prepare(`SELECT a.*,ar.name artist_name,ar.artist_type FROM artworks a JOIN artists ar ON ar.id=a.artist_id WHERE a.id=? AND a.status='approved' AND ar.status='approved'`).get(req.params.id);if(!x)return res.status(404).json({error:'Artwork not found'});recordArtistStat(x.artist_id,'views');res.json(x)});
app.get('/api/artists',(req,res)=>{const type=req.query.type||'';const age=req.query.age_group||'';let sql=`SELECT id,name,specialty,bio,image_url,artist_type,age_group,registration_paid FROM artists WHERE status='approved'`;const p=[];if(type){sql+=' AND artist_type=?';p.push(type)}if(age){sql+=' AND age_group=?';p.push(age)}sql+=' ORDER BY name';res.json(db.prepare(sql).all(...p))});
app.get('/api/artists/:id',(req,res)=>{const x=db.prepare("SELECT id,name,specialty,bio,image_url FROM artists WHERE id=? AND status='approved'").get(req.params.id);if(!x)return res.status(404).json({error:'Artist not found'});x.artworks=db.prepare(`SELECT id,title,medium,size,price,image_url,availability,age_group FROM artworks WHERE artist_id=? AND status='approved' ORDER BY created_at DESC`).all(req.params.id);res.json(x)});
app.get('/api/supplies',(req,res)=>{let sql='SELECT * FROM supplies WHERE active=1';const q='%'+(req.query.q||'')+'%';if(req.query.q){sql+=' AND (name LIKE ? OR category LIKE ?)';return res.json(db.prepare(sql+' ORDER BY created_at DESC').all(q,q))}res.json(db.prepare(sql+' ORDER BY created_at DESC').all())});
app.get('/api/supplies/:id',(req,res)=>{const x=db.prepare('SELECT * FROM supplies WHERE id=? AND active=1').get(req.params.id);if(!x)return res.status(404).json({error:'Supply not found'});res.json(x)});
app.post('/api/artist/apply',auth,(req,res)=>{try{const u=req.session.user;const {name,specialty,bio,image_url,artist_type='professional',age_group='adult',guardian_name='',guardian_phone=''}=req.body;const rule=tierRule(artist_type);if(artist_type==='kid'&&(!guardian_name||!guardian_phone))return res.status(400).json({error:'Young artist registration requires parent/guardian details'});const existing=db.prepare('SELECT id FROM artists WHERE user_id=?').get(u.id);if(existing)return res.status(409).json({error:'Application already exists'});if(artist_type!=='signature')return res.status(402).json({error:'Complete registration payment before submitting your artist application'});const info=db.prepare('INSERT INTO artists(user_id,name,specialty,bio,image_url,artist_type,age_group,guardian_name,guardian_phone,registration_paid,status) VALUES(?,?,?,?,?,?,?,?,?,?,?)').run(u.id,name||u.name,specialty||'',bio||'',image_url||'',artist_type,'adult',guardian_name,guardian_phone,1,'pending');db.prepare("UPDATE users SET role='artist' WHERE id=?").run(u.id);req.session.user.role='artist';res.json({id:info.lastInsertRowid,status:'pending',payment_required:false,minimum_works:rule.min,maximum_works:rule.max})}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/artist/dashboard',auth,role('artist'),(req,res)=>{const ar=db.prepare('SELECT * FROM artists WHERE user_id=?').get(req.session.user.id);const artworks=ar?db.prepare('SELECT * FROM artworks WHERE artist_id=? ORDER BY created_at DESC').all(ar.id):[];const orders=ar?db.prepare(`SELECT o.id,o.total,o.status,o.created_at,oi.title,oi.price,oi.quantity FROM orders o JOIN order_items oi ON oi.order_id=o.id WHERE oi.artist_id=? ORDER BY o.created_at DESC`).all(ar.id):[];res.json({artist:ar,artworks,orders,listing_fee:setting('artist_listing_fee'),commission_percent:setting('sales_commission_percent')})});
app.post('/api/artist/artworks',auth,role('artist'),upload.single('image'),(req,res)=>{const ar=db.prepare('SELECT * FROM artists WHERE user_id=?').get(req.session.user.id);if(!ar)return res.status(400).json({error:'Submit an artist application first'});const rule=tierRule(ar.artist_type);const count=db.prepare('SELECT COUNT(*) c FROM artworks WHERE artist_id=?').get(ar.id).c;if(ar.artist_type!=='signature'&&!ar.registration_paid)return res.status(402).json({error:'Complete registration payment before uploading artwork'});if(count>=rule.max)return res.status(400).json({error:`Your ${rule.label} plan allows a maximum of ${rule.max} works`});if(!req.file)return res.status(400).json({error:'Image is required'});const age=ar.artist_type==='kid'?'kid':'adult';const info=db.prepare('INSERT INTO artworks(artist_id,title,medium,size,price,description,image_url,availability,age_group,status) VALUES(?,?,?,?,?,?,?,?,?,?)').run(ar.id,req.body.title,req.body.medium,req.body.size||'',Number(req.body.price),req.body.description||'',`/uploads/${req.file.filename}`,'Available',age,'pending');res.json({id:info.lastInsertRowid,status:'pending',minimum_works:rule.min,maximum_works:rule.max})});
app.post('/api/orders', (req,res)=>{try{const {customer_name,customer_email,whatsapp,address,items=[]}=req.body;if(!items.length)return res.status(400).json({error:'Cart is empty'});const arts=items.filter(i=>i.type==='art'),sups=items.filter(i=>i.type==='supply');const artIds=arts.map(i=>Number(i.id)).filter(Boolean),supIds=sups.map(i=>Number(i.id)).filter(Boolean);const artRows=artIds.length?db.prepare(`SELECT a.id,a.title,a.price,a.artist_id FROM artworks a WHERE a.status='approved' AND a.id IN (${artIds.map(()=>'?').join(',')})`).all(...artIds):[];const supRows=supIds.length?db.prepare(`SELECT id,name title,price,stock FROM supplies WHERE active=1 AND id IN (${supIds.map(()=>'?').join(',')})`).all(...supIds):[];if(artRows.length!==new Set(artIds).size||supRows.length!==new Set(supIds).size)return res.status(400).json({error:'One or more items are unavailable'});let subtotal=0;const norm=[];arts.forEach(i=>{const a=artRows.find(x=>x.id===Number(i.id));const q=Math.max(1,Number(i.quantity)||1);subtotal+=a.price*q;norm.push({...a,type:'art',quantity:q})});sups.forEach(i=>{const s=supRows.find(x=>x.id===Number(i.id));const q=Math.max(1,Number(i.quantity)||1);if(q>s.stock)return res.status(400).json({error:s.title+' does not have enough stock'});subtotal+=s.price*q;norm.push({...s,type:'supply',quantity:q})});const commission=arts.reduce((sum,i)=>{const a=artRows.find(x=>x.id===Number(i.id));return sum+a.price*Math.max(1,Number(i.quantity)||1)*setting('sales_commission_percent')/100},0);const tx=db.transaction(()=>{const o=db.prepare('INSERT INTO orders(user_id,customer_name,customer_email,whatsapp,address,total,commission) VALUES(?,?,?,?,?,?,?)').run(req.session.user?.id||null,customer_name||'',customer_email||'',whatsapp||'',address||'',subtotal,commission);const ins=db.prepare('INSERT INTO order_items(order_id,item_type,item_id,title,price,quantity,artist_id) VALUES(?,?,?,?,?,?,?)');const upd=db.prepare('UPDATE supplies SET stock=stock-? WHERE id=?');norm.forEach(i=>{ins.run(o.lastInsertRowid,i.type,i.id,i.title,i.price,i.quantity,i.artist_id||null);if(i.type==='supply')upd.run(i.quantity,i.id);if(i.type==='art')recordArtistStat(i.artist_id,'sales',i.quantity)});return o.lastInsertRowid})();res.json({order_id:tx,total:subtotal,commission,items:norm})}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/orders',auth,(req,res)=>res.json(db.prepare('SELECT * FROM orders WHERE user_id=? ORDER BY created_at DESC').all(req.session.user.id)));

// Artist registration payments: kid ₦4,000/$3, professional ₦13,000/$10, signature free.
app.get('/api/artist/tiers',(req,res)=>res.json(TIER_RULES));
app.post('/api/artist/registration/payment',auth,rateLimit(6,60000),async(req,res)=>{try{const u=req.session.user;const type=['kid','professional','signature'].includes(req.body.artist_type)?req.body.artist_type:'professional';const currency=['NGN','USD'].includes(req.body.currency)?req.body.currency:'NGN';const rule=tierRule(type);const amount=rule.fee[currency];if(!amount)return res.json({free:true,artist_type:type,minimum_works:rule.min,maximum_works:rule.max});const existing=db.prepare('SELECT id FROM artists WHERE user_id=?').get(u.id);if(existing)return res.status(409).json({error:'Application already exists'});if(type==='kid'&&(!req.body.guardian_name||!req.body.guardian_phone))return res.status(400).json({error:'Parent/guardian details are required for kid artist registration'});const reference='AAS-'+u.id+'-'+Date.now()+'-'+crypto.randomBytes(4).toString('hex');const origin=req.protocol+'://'+req.get('host');const meta={name:req.body.name||u.name,specialty:req.body.specialty||'',bio:req.body.bio||'',image_url:req.body.image_url||'',artist_type:type,age_group:type==='kid'?'4-18':'adult',guardian_name:req.body.guardian_name||'',guardian_phone:req.body.guardian_phone||''};db.prepare('INSERT INTO transactions(user_id,provider,reference,status,amount,currency,purpose,artist_type,metadata) VALUES(?,?,?,?,?,?,?,?,?)').run(u.id,'paystack',reference,'pending',amount,currency,'artist_registration',type,JSON.stringify(meta));const data=await paystack('/transaction/initialize',{method:'POST',body:JSON.stringify({email:u.email,amount:String(Math.round(amount*100)),currency,reference,callback_url:origin+'/api/artist/payment/callback',metadata:meta})});res.json({free:false,authorization_url:data.data.authorization_url,reference,artist_type:type,minimum_works:rule.min,maximum_works:rule.max,amount,currency})}catch(e){res.status(500).json({error:e.message})}});
async function finalizeArtistPayment(reference,sessionUser=null){const tx=db.prepare("SELECT * FROM transactions WHERE reference=? AND purpose='artist_registration'").get(reference);if(!tx)return false;if(tx.status==='success'){db.prepare("UPDATE users SET role='artist' WHERE id=?").run(tx.user_id);if(sessionUser?.id===tx.user_id)sessionUser.role='artist';return true;}const data=await paystack('/transaction/verify/'+encodeURIComponent(reference));const ok=data.data?.status==='success'&&Number(data.data.amount)===Math.round(tx.amount*100)&&data.data.currency===tx.currency;if(!ok)return false;db.prepare("UPDATE transactions SET status='success' WHERE id=?").run(tx.id);let ar=db.prepare('SELECT id FROM artists WHERE user_id=?').get(tx.user_id);if(!ar){const m=JSON.parse(tx.metadata||'{}');const info=db.prepare('INSERT INTO artists(user_id,name,specialty,bio,image_url,artist_type,age_group,guardian_name,guardian_phone,registration_paid,payment_reference,registration_currency,registration_amount,status) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(tx.user_id,m.name||'Artist',m.specialty||'',m.bio||'',m.image_url||'',tx.artist_type||'professional',m.age_group||'adult',m.guardian_name||'',m.guardian_phone||'',1,reference,tx.currency,tx.amount,'pending');ar={id:info.lastInsertRowid}}else{db.prepare('UPDATE artists SET registration_paid=1,payment_reference=?,registration_currency=?,registration_amount=? WHERE id=?').run(reference,tx.currency,tx.amount,ar.id)}db.prepare("UPDATE users SET role='artist' WHERE id=?").run(tx.user_id);if(sessionUser?.id===tx.user_id)sessionUser.role='artist';const paidUser=db.prepare('SELECT name,email FROM users WHERE id=?').get(tx.user_id);const meta=JSON.parse(tx.metadata||'{}');sendEmail({to:OWNER_EMAIL,subject:'AfricanArtistShop — Artist Registration Payment #'+reference,html:'<h2>Artist registration payment received</h2><p><b>Artist:</b> '+escHtml(meta.name||paidUser?.name||'Artist')+'</p><p><b>Type:</b> '+escHtml(tx.artist_type||'professional')+'<br><b>Amount:</b> '+escHtml(tx.currency)+' '+Number(tx.amount).toLocaleString()+'<br><b>Reference:</b> '+escHtml(reference)+'</p><p><b>Customer email:</b> '+escHtml(paidUser?.email||'')+'</p>'}).catch(()=>{});if(paidUser?.email)sendEmail({to:paidUser.email,subject:'AfricanArtistShop — Artist registration payment confirmed',html:'<h2>Payment confirmed</h2><p>Your '+escHtml(tx.artist_type||'professional')+' artist registration payment has been verified.</p><p><b>Reference:</b> '+escHtml(reference)+'</p><p>Your artist application is now in the review process. You can sign in to access your artist dashboard and upload your works.</p>'}).catch(()=>{});return true}
app.get('/api/artist/payment/callback',async(req,res)=>{try{const ok=await finalizeArtistPayment(req.query.reference,req.session.user||null);res.redirect('/?artist_payment='+(ok?'success':'failed'))}catch(e){res.redirect('/?artist_payment=failed')}});
app.post('/api/paystack/webhook',(req,res)=>{try{const secret=process.env.PAYSTACK_SECRET_KEY;if(!secret)return res.sendStatus(200);const sig=req.headers['x-paystack-signature'];const hash=crypto.createHmac('sha512',secret).update(req.rawBody||Buffer.from(JSON.stringify(req.body))).digest('hex');if(!sig||hash!==sig)return res.sendStatus(401);if(req.body.event==='charge.success'&&req.body.data?.reference){finalizeArtistPayment(req.body.data.reference).catch(()=>{});}res.sendStatus(200)}catch(e){res.sendStatus(200)}});
app.get('/api/top-artists',(req,res)=>{const rows=db.prepare(`SELECT ar.id,ar.name,ar.specialty,ar.image_url,ar.artist_type,ar.age_group,COALESCE(s.views,0) views,COALESCE(s.sales,0) sales,(COALESCE(s.views,0)+COALESCE(s.sales,0)*10) score FROM artists ar LEFT JOIN artist_daily_stats s ON s.artist_id=ar.id AND s.day=? WHERE ar.status='approved' ORDER BY score DESC,ar.name LIMIT 30`).all(today());const groups={kid:[],professional:[],signature:[]};rows.forEach(x=>{if(groups[x.artist_type])groups[x.artist_type].push(x)});const out=[];let i=0;while(out.length<10&&(groups.kid.length||groups.professional.length||groups.signature.length)){const k=['kid','professional','signature'][i%3];if(groups[k].length)out.push(groups[k].shift());i++}rows.forEach(x=>{if(out.length<10&&!out.some(y=>y.id===x.id))out.push(x)});res.json(out.slice(0,10))});
app.post('/api/training-requests',async(req,res)=>{try{const {child_name,child_age,guardian_name,guardian_phone,email,location,training_type,notes}=req.body;if(!child_name||!Number.isInteger(Number(child_age))||Number(child_age)<4||Number(child_age)>18||!guardian_name||!guardian_phone)return res.status(400).json({error:'Training registration requires a young artist aged 4–18 plus guardian details'});const r=db.prepare('INSERT INTO training_requests(user_id,child_name,child_age,guardian_name,guardian_phone,email,location,training_type,notes) VALUES(?,?,?,?,?,?,?,?,?)').run(req.session.user?.id||null,child_name,Number(child_age),guardian_name,guardian_phone,email||'',location||'',training_type||'',notes||'');const ref=r.lastInsertRowid;sendEmail({to:OWNER_EMAIL,subject:'AfricanArtistShop — Young Artist Training Request #'+ref,html:'<h2>New Young Artist Training Request</h2><p><b>Reference:</b> #'+ref+'</p><p><b>Young artist:</b> '+escHtml(child_name)+'<br><b>Age:</b> '+Number(child_age)+'</p><p><b>Parent/Guardian:</b> '+escHtml(guardian_name)+'<br><b>Phone:</b> '+escHtml(guardian_phone)+'</p><p><b>Email:</b> '+escHtml(email||'Not supplied')+'<br><b>Location:</b> '+escHtml(location||'Not supplied')+'<br><b>Training:</b> '+escHtml(training_type||'Not supplied')+'</p><p>'+escHtml(notes||'')+'</p>'}).catch(()=>{});if(email)sendEmail({to:email,subject:'AfricanArtistShop — Training Request Received #'+ref,html:'<h2>Training request received</h2><p>Thank you. We received the young artist training request. Your reference is <b>#'+ref+'</b>.</p><p>Our team will review the request and contact the parent/guardian using the details provided.</p>'}).catch(()=>{});res.json({id:ref,status:'pending',email_notice:!!process.env.RESEND_API_KEY})}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/admin/stats',auth,role('admin'),(req,res)=>res.json({users:db.prepare('SELECT COUNT(*) c FROM users').get().c,artists:db.prepare('SELECT COUNT(*) c FROM artists').get().c,artworks:db.prepare('SELECT COUNT(*) c FROM artworks').get().c,orders:db.prepare('SELECT COUNT(*) c FROM orders').get().c,supplies:db.prepare('SELECT COUNT(*) c FROM supplies WHERE active=1').get().c}));
app.get('/api/admin/pending',auth,role('admin'),(req,res)=>res.json({artists:db.prepare("SELECT * FROM artists WHERE status='pending'").all(),artworks:db.prepare(`SELECT a.*,ar.name artist_name FROM artworks a JOIN artists ar ON ar.id=a.artist_id WHERE a.status='pending'`).all()}));
app.patch('/api/admin/artists/:id',auth,role('admin'),(req,res)=>{const status=['approved','rejected','pending'].includes(req.body.status)?req.body.status:'pending';const ar=db.prepare('SELECT * FROM artists WHERE id=?').get(req.params.id);if(!ar)return res.status(404).json({error:'Artist not found'});if(status==='approved'){const rule=tierRule(ar.artist_type);const count=db.prepare('SELECT COUNT(*) c FROM artworks WHERE artist_id=? AND status IN (\'approved\',\'pending\')').get(ar.id).c;if(ar.artist_type!=='signature'&&!ar.registration_paid)return res.status(402).json({error:'Registration payment has not been verified'});if(count<rule.min||count>rule.max)return res.status(400).json({error:`${rule.label} must showcase between ${rule.min} and ${rule.max} works before approval`})}db.prepare('UPDATE artists SET status=? WHERE id=?').run(status,req.params.id);res.json({ok:true,status})});
app.patch('/api/admin/artworks/:id',auth,role('admin'),(req,res)=>{const status=['approved','rejected','pending'].includes(req.body.status)?req.body.status:'pending';db.prepare('UPDATE artworks SET status=? WHERE id=?').run(status,req.params.id);res.json({ok:true,status})});
app.patch('/api/admin/supplies/:id',auth,role('admin'),(req,res)=>{const {price,stock,active}=req.body;db.prepare('UPDATE supplies SET price=COALESCE(?,price),stock=COALESCE(?,stock),active=COALESCE(?,active) WHERE id=?').run(price??null,stock??null,active??null,req.params.id);res.json({ok:true})});
app.use('/uploads',express.static(uploadDir)); app.use(express.static(path.join(__dirname,'public'))); app.get('/*splat',(req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));
app.listen(PORT,()=>console.log(`AfricanArtistShop running on port ${PORT}`));