require('dotenv').config();
const path=require('path'); const fs=require('fs');
const express=require('express'); const session=require('express-session');
const bcrypt=require('bcryptjs'); const multer=require('multer'); const Database=require('better-sqlite3');
const app=express(); const PORT=process.env.PORT||3000;
const DB_PATH=process.env.DB_PATH||path.join(__dirname,'africanartistshop.db');
const uploadDir=path.join(__dirname,'public','uploads'); fs.mkdirSync(uploadDir,{recursive:true});
const db=new Database(DB_PATH); db.pragma('journal_mode=WAL');
app.use(express.json()); app.use(express.urlencoded({extended:true}));
app.use(session({secret:process.env.SESSION_SECRET||'change-me',resave:false,saveUninitialized:false,cookie:{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production'}}));
const storage=multer.diskStorage({destination:uploadDir,filename:(req,file,cb)=>cb(null,Date.now()+'-'+file.originalname.replace(/[^a-zA-Z0-9._-]/g,'_'))});
const upload=multer({storage,limits:{fileSize:8*1024*1024}});
function init(){
db.exec(`
CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,email TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'customer',created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS artists(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER UNIQUE,name TEXT NOT NULL,specialty TEXT,bio TEXT,image_url TEXT,artist_type TEXT DEFAULT 'professional',age_group TEXT DEFAULT 'adult',guardian_name TEXT,guardian_phone TEXT,status TEXT NOT NULL DEFAULT 'pending',created_at TEXT DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(id));
CREATE TABLE IF NOT EXISTS artworks(id INTEGER PRIMARY KEY AUTOINCREMENT,artist_id INTEGER NOT NULL,title TEXT NOT NULL,medium TEXT NOT NULL,size TEXT,price REAL NOT NULL,description TEXT,image_url TEXT NOT NULL,availability TEXT DEFAULT 'Available',age_group TEXT DEFAULT 'adult',status TEXT NOT NULL DEFAULT 'pending',created_at TEXT DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(artist_id) REFERENCES artists(id));
CREATE TABLE IF NOT EXISTS supplies(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,category TEXT NOT NULL,description TEXT,image_url TEXT NOT NULL,price REAL NOT NULL,stock INTEGER DEFAULT 0,unit TEXT DEFAULT 'piece',active INTEGER DEFAULT 1,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS orders(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER,customer_name TEXT,customer_email TEXT,whatsapp TEXT,address TEXT,total REAL NOT NULL,listing_fees REAL DEFAULT 0,commission REAL DEFAULT 0,status TEXT DEFAULT 'pending',created_at TEXT DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(id));
CREATE TABLE IF NOT EXISTS order_items(id INTEGER PRIMARY KEY AUTOINCREMENT,order_id INTEGER,item_type TEXT NOT NULL,item_id INTEGER,title TEXT,price REAL,quantity INTEGER,artist_id INTEGER,FOREIGN KEY(order_id) REFERENCES orders(id));
CREATE TABLE IF NOT EXISTS transactions(id INTEGER PRIMARY KEY AUTOINCREMENT,order_id INTEGER,provider TEXT,reference TEXT,status TEXT,amount REAL,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY,value TEXT);
`);
const set=(k,v)=>db.prepare('INSERT OR IGNORE INTO settings(key,value) VALUES(?,?)').run(k,String(v));
set('artist_listing_fee','5000'); set('sales_commission_percent','10');
const admin=db.prepare('SELECT id FROM users WHERE email=?').get('admin@africanartistshop.com');
if(!admin) db.prepare('INSERT INTO users(name,email,password_hash,role) VALUES(?,?,?,?)').run('AfricanArtistShop Admin','admin@africanartistshop.com',bcrypt.hashSync('demo1234',10),'admin');
let a=db.prepare('SELECT id FROM users WHERE email=?').get('peace@example.com');
if(!a){const info=db.prepare('INSERT INTO users(name,email,password_hash,role) VALUES(?,?,?,?)').run('Peace Mojibola','peace@example.com',bcrypt.hashSync('demo1234',10),'artist');const ar=db.prepare('INSERT INTO artists(user_id,name,specialty,bio,image_url,status) VALUES(?,?,?,?,?,?)').run(info.lastInsertRowid,'Peace Mojibola','Painting','Demo artist account. Replace this content with the artist profile.','https://images.unsplash.com/photo-1577083288073-40892c0860a4?auto=format&fit=crop&w=900&q=80','approved');db.prepare('INSERT INTO artworks(artist_id,title,medium,size,price,description,image_url,availability,status) VALUES(?,?,?,?,?,?,?,?,?)').run(ar.lastInsertRowid,'African Light','Painting','24 x 36 in',85000,'Demo artwork. Replace with licensed/owned work.','https://images.unsplash.com/photo-1549490349-8643362247b5?auto=format&fit=crop&w=900&q=80','Available','approved');}
if(db.prepare('SELECT COUNT(*) c FROM supplies').get().c===0){
const ins=db.prepare('INSERT INTO supplies(name,category,description,image_url,price,stock,unit) VALUES(?,?,?,?,?,?,?)');
[
['Acrylic Paint Set','Paints','Rich starter acrylic set for canvas and mixed-media work.','https://images.unsplash.com/photo-1577083288073-40892c0860a4?auto=format&fit=crop&w=900&q=80',18500,20,'set'],
['Artist Brush Collection','Brushes','Assorted round, flat and detail brushes for artists.','https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&w=900&q=80',9500,30,'pack'],
['Cotton Canvas 24 × 36 in','Canvas','Primed cotton canvas ready for painting.','https://images.unsplash.com/photo-1547891654-e66ed7ebb968?auto=format&fit=crop&w=900&q=80',12000,25,'piece'],
['Wooden Tabletop Easel','Easels','Compact wooden easel for studio or tabletop painting.','https://images.unsplash.com/photo-1541961017774-22349e4a1262?auto=format&fit=crop&w=900&q=80',22000,12,'piece'],
['Watercolour Paper Pad','Paper','Acid-free paper for watercolour and ink studies.','https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&w=900&q=80',7500,35,'pad'],
['Palette Knife Set','Tools','Metal palette knives for texture and impasto techniques.','https://images.unsplash.com/photo-1549490349-8643362247b5?auto=format&fit=crop&w=900&q=80',6500,18,'set']
].forEach(x=>ins.run(...x));
}}
init();
function auth(req,res,next){if(!req.session.user)return res.status(401).json({error:'Authentication required'});next()}
function role(r){return (req,res,next)=>{if(!req.session.user||req.session.user.role!==r)return res.status(403).json({error:'Forbidden'});next()}}
function setting(k){return Number(db.prepare('SELECT value FROM settings WHERE key=?').get(k)?.value||0)}
app.get('/api/health',(req,res)=>res.json({ok:true}));
app.get('/api/me',(req,res)=>res.json({user:req.session.user||null}));
app.post('/api/register',(req,res)=>{try{const {name,email,password}=req.body;if(!name||!email||!password)return res.status(400).json({error:'Name, email and password are required'});const exists=db.prepare('SELECT id FROM users WHERE email=?').get(email.toLowerCase());if(exists)return res.status(409).json({error:'Email already registered'});const info=db.prepare('INSERT INTO users(name,email,password_hash,role) VALUES(?,?,?,?)').run(name,email.toLowerCase(),bcrypt.hashSync(password,10),'customer');const user={id:info.lastInsertRowid,name,email:email.toLowerCase(),role:'customer'};req.session.user=user;res.json(user)}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/login',(req,res)=>{const {email,password}=req.body;const u=db.prepare('SELECT * FROM users WHERE email=?').get((email||'').toLowerCase());if(!u||!bcrypt.compareSync(password||'',u.password_hash))return res.status(401).json({error:'Invalid email or password'});const user={id:u.id,name:u.name,email:u.email,role:u.role};req.session.user=user;res.json(user)});
app.post('/api/logout',(req,res)=>req.session.destroy(()=>res.json({ok:true})));
app.get('/api/artworks',(req,res)=>{const q='%'+(req.query.q||'')+'%';const m=req.query.medium||'';let sql=`SELECT a.*,ar.name artist_name FROM artworks a JOIN artists ar ON ar.id=a.artist_id WHERE a.status='approved' AND ar.status='approved' AND (a.title LIKE ? OR a.medium LIKE ? OR ar.name LIKE ?)`;let params=[q,q,q];if(m){sql+=' AND a.medium=?';params.push(m)}if(req.query.age){sql+=' AND a.age_group=?';params.push(req.query.age)}sql+=' ORDER BY a.created_at DESC';res.json(db.prepare(sql).all(...params))});
app.get('/api/artworks/:id',(req,res)=>{const x=db.prepare(`SELECT a.*,ar.name artist_name FROM artworks a JOIN artists ar ON ar.id=a.artist_id WHERE a.id=? AND a.status='approved' AND ar.status='approved'`).get(req.params.id);if(!x)return res.status(404).json({error:'Artwork not found'});res.json(x)});
app.get('/api/artists',(req,res)=>{const type=req.query.type||'';const age=req.query.age_group||'';let sql=`SELECT id,name,specialty,bio,image_url,artist_type,age_group FROM artists WHERE status='approved'`;const p=[];if(type){sql+=' AND artist_type=?';p.push(type)}if(age){sql+=' AND age_group=?';p.push(age)}sql+=' ORDER BY name';res.json(db.prepare(sql).all(...p))});
app.get('/api/artists/:id',(req,res)=>{const x=db.prepare("SELECT id,name,specialty,bio,image_url FROM artists WHERE id=? AND status='approved'").get(req.params.id);if(!x)return res.status(404).json({error:'Artist not found'});x.artworks=db.prepare(`SELECT id,title,medium,size,price,image_url,availability,age_group FROM artworks WHERE artist_id=? AND status='approved' ORDER BY created_at DESC`).all(req.params.id);res.json(x)});
app.get('/api/supplies',(req,res)=>{let sql='SELECT * FROM supplies WHERE active=1';const q='%'+(req.query.q||'')+'%';if(req.query.q){sql+=' AND (name LIKE ? OR category LIKE ?)';return res.json(db.prepare(sql+' ORDER BY created_at DESC').all(q,q))}res.json(db.prepare(sql+' ORDER BY created_at DESC').all())});
app.get('/api/supplies/:id',(req,res)=>{const x=db.prepare('SELECT * FROM supplies WHERE id=? AND active=1').get(req.params.id);if(!x)return res.status(404).json({error:'Supply not found'});res.json(x)});
app.post('/api/artist/apply',auth,(req,res)=>{const u=req.session.user;const {name,specialty,bio,image_url,artist_type='professional',age_group='adult',guardian_name='',guardian_phone=''}=req.body;const existing=db.prepare('SELECT id FROM artists WHERE user_id=?').get(u.id);if(existing)return res.status(409).json({error:'Application already exists'});const info=db.prepare('INSERT INTO artists(user_id,name,specialty,bio,image_url,artist_type,age_group,guardian_name,guardian_phone,status) VALUES(?,?,?,?,?,?,?,?,?,?)').run(u.id,name||u.name,specialty||'',bio||'',image_url||'',artist_type,age_group,guardian_name,guardian_phone,'pending');db.prepare("UPDATE users SET role='artist' WHERE id=?").run(u.id);req.session.user.role='artist';res.json({id:info.lastInsertRowid,status:'pending'})});
app.get('/api/artist/dashboard',auth,role('artist'),(req,res)=>{const ar=db.prepare('SELECT * FROM artists WHERE user_id=?').get(req.session.user.id);const artworks=ar?db.prepare('SELECT * FROM artworks WHERE artist_id=? ORDER BY created_at DESC').all(ar.id):[];const orders=ar?db.prepare(`SELECT o.id,o.total,o.status,o.created_at,oi.title,oi.price,oi.quantity FROM orders o JOIN order_items oi ON oi.order_id=o.id WHERE oi.artist_id=? ORDER BY o.created_at DESC`).all(ar.id):[];res.json({artist:ar,artworks,orders,listing_fee:setting('artist_listing_fee'),commission_percent:setting('sales_commission_percent')})});
app.post('/api/artist/artworks',auth,role('artist'),upload.single('image'),(req,res)=>{const ar=db.prepare('SELECT * FROM artists WHERE user_id=?').get(req.session.user.id);if(!ar)return res.status(400).json({error:'Submit an artist application first'});if(!req.file)return res.status(400).json({error:'Image is required'});const age=['kid','adult'].includes(req.body.age_group)?req.body.age_group:'adult';const info=db.prepare('INSERT INTO artworks(artist_id,title,medium,size,price,description,image_url,availability,age_group,status) VALUES(?,?,?,?,?,?,?,?,?,?)').run(ar.id,req.body.title,req.body.medium,req.body.size||'',Number(req.body.price),req.body.description||'',`/uploads/${req.file.filename}`,'Available',age,'pending');res.json({id:info.lastInsertRowid,status:'pending',listing_fee:setting('artist_listing_fee')})});
app.post('/api/orders', (req,res)=>{try{const {customer_name,customer_email,whatsapp,address,items=[]}=req.body;if(!items.length)return res.status(400).json({error:'Cart is empty'});const arts=items.filter(i=>i.type==='art'),sups=items.filter(i=>i.type==='supply');const artIds=arts.map(i=>Number(i.id)).filter(Boolean),supIds=sups.map(i=>Number(i.id)).filter(Boolean);const artRows=artIds.length?db.prepare(`SELECT a.id,a.title,a.price,a.artist_id FROM artworks a WHERE a.status='approved' AND a.id IN (${artIds.map(()=>'?').join(',')})`).all(...artIds):[];const supRows=supIds.length?db.prepare(`SELECT id,name title,price,stock FROM supplies WHERE active=1 AND id IN (${supIds.map(()=>'?').join(',')})`).all(...supIds):[];if(artRows.length!==new Set(artIds).size||supRows.length!==new Set(supIds).size)return res.status(400).json({error:'One or more items are unavailable'});let subtotal=0;const norm=[];arts.forEach(i=>{const a=artRows.find(x=>x.id===Number(i.id));const q=Math.max(1,Number(i.quantity)||1);subtotal+=a.price*q;norm.push({...a,type:'art',quantity:q})});sups.forEach(i=>{const s=supRows.find(x=>x.id===Number(i.id));const q=Math.max(1,Number(i.quantity)||1);if(q>s.stock)return res.status(400).json({error:s.title+' does not have enough stock'});subtotal+=s.price*q;norm.push({...s,type:'supply',quantity:q})});const commission=arts.reduce((sum,i)=>{const a=artRows.find(x=>x.id===Number(i.id));return sum+a.price*Math.max(1,Number(i.quantity)||1)*setting('sales_commission_percent')/100},0);const tx=db.transaction(()=>{const o=db.prepare('INSERT INTO orders(user_id,customer_name,customer_email,whatsapp,address,total,commission) VALUES(?,?,?,?,?,?,?)').run(req.session.user?.id||null,customer_name||'',customer_email||'',whatsapp||'',address||'',subtotal,commission);const ins=db.prepare('INSERT INTO order_items(order_id,item_type,item_id,title,price,quantity,artist_id) VALUES(?,?,?,?,?,?,?)');const upd=db.prepare('UPDATE supplies SET stock=stock-? WHERE id=?');norm.forEach(i=>{ins.run(o.lastInsertRowid,i.type,i.id,i.title,i.price,i.quantity,i.artist_id||null);if(i.type==='supply')upd.run(i.quantity,i.id)});return o.lastInsertRowid})();res.json({order_id:tx,total:subtotal,commission,items:norm})}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/orders',auth,(req,res)=>res.json(db.prepare('SELECT * FROM orders WHERE user_id=? ORDER BY created_at DESC').all(req.session.user.id)));
app.get('/api/admin/stats',auth,role('admin'),(req,res)=>res.json({users:db.prepare('SELECT COUNT(*) c FROM users').get().c,artists:db.prepare('SELECT COUNT(*) c FROM artists').get().c,artworks:db.prepare('SELECT COUNT(*) c FROM artworks').get().c,orders:db.prepare('SELECT COUNT(*) c FROM orders').get().c,supplies:db.prepare('SELECT COUNT(*) c FROM supplies WHERE active=1').get().c}));
app.get('/api/admin/pending',auth,role('admin'),(req,res)=>res.json({artists:db.prepare("SELECT * FROM artists WHERE status='pending'").all(),artworks:db.prepare(`SELECT a.*,ar.name artist_name FROM artworks a JOIN artists ar ON ar.id=a.artist_id WHERE a.status='pending'`).all()}));
app.patch('/api/admin/artists/:id',auth,role('admin'),(req,res)=>{const status=['approved','rejected','pending'].includes(req.body.status)?req.body.status:'pending';db.prepare('UPDATE artists SET status=? WHERE id=?').run(status,req.params.id);res.json({ok:true,status})});
app.patch('/api/admin/artworks/:id',auth,role('admin'),(req,res)=>{const status=['approved','rejected','pending'].includes(req.body.status)?req.body.status:'pending';db.prepare('UPDATE artworks SET status=? WHERE id=?').run(status,req.params.id);res.json({ok:true,status})});
app.patch('/api/admin/supplies/:id',auth,role('admin'),(req,res)=>{const {price,stock,active}=req.body;db.prepare('UPDATE supplies SET price=COALESCE(?,price),stock=COALESCE(?,stock),active=COALESCE(?,active) WHERE id=?').run(price??null,stock??null,active??null,req.params.id);res.json({ok:true})});
app.use('/uploads',express.static(uploadDir)); app.use(express.static(path.join(__dirname,'public'))); app.get('/*splat',(req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));
app.listen(PORT,()=>console.log(`AfricanArtistShop running on port ${PORT}`));